version: '2'

services:

  alien_armpit:    
    container_name: alien_armpit
    image: eosdaq/alien_armpit    
    build: .
    ports:
      - '3000:3000'
    
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '3031:80'

  