version: '3'

services:
  alien-armpit:
    container_name: alien-armpit
    ports:
      - "3000:3000"
    build: .
    networks:
      - eos_net
  tiffanyblue:
    ports:
      - "18890:1323"
    image: eosdaq/tiffanyblue
    networks:
      - eos_net
    depends_on:
      - eos_db
    environment:
     - DB_HOST=eos_db
     - DB_PORT=3306
     - DB_NAME=eosdaq
     - AWS_ON=false
     - DB_USER=eosdaquser
     - DB_PASS=eosdaqvotmdnjem
  burgundy:
    ports:
      - "18889:1313"
    image: eosdaq/burgundy
    networks:
      - eos_net
    # deploy:
    #   replicas: 1
    depends_on:
      - eos_db
    environment:
      - EOSDAQMANAGE=${EOSDAQMANAGE}
      - EOS_HOST=http://local_nodeos
      - EOS_PORT=8888
      - DB_HOST=eos_db
      - DB_USER=eosdaquser
      - DB_PASS=eosdaqvotmdnjem
      - ENV=devel
  eos_db:
    ports:
      - "3306:3306"
    image: mariadb
    networks:
      - eos_net
    environment:
        MYSQL_ROOT_PASSWORD: eosdaqvotmdnjem
        MYSQL_DATABASE: eosdaq
        MYSQL_USER: eosdaquser
        MYSQL_PASSWORD: eosdaqvotmdnjem
networks:
  eos_net:
    external: true


  